set wshshell = wscript.CreateObject("wscript.shell")

set computerVoice  = CreateObject("SAPI.spvoice")

wscript.sleep 3000
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "p6"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "t"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "p"
WScript.Sleep 300
WshShell.SendKeys "3a"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "O"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "6s"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "p6"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "t"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "p"
WScript.Sleep 300
WshShell.SendKeys "3a"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "W"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "6p"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "p6"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "t"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "p"
WScript.Sleep 300
WshShell.SendKeys "3a"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "O"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "6s"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "p6"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "t"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "p"
WScript.Sleep 300
WshShell.SendKeys "3a"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "W"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "6p"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "t"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "p"
WScript.Sleep 300
WshShell.SendKeys "3a"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "W"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "6p"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "8f"
WScript.Sleep 300
WshShell.SendKeys "w"
WScript.Sleep 300
WshShell.SendKeys "t"
WScript.Sleep 300
WshShell.SendKeys "o"
WScript.Sleep 300
WshShell.SendKeys "g"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "5d"
WScript.Sleep 300
WshShell.SendKeys "w"
WScript.Sleep 300
WshShell.SendKeys "r"
WScript.Sleep 300
WshShell.SendKeys "i"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "6s"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "3a"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "x"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "p6"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "t"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "p"
WScript.Sleep 300
WshShell.SendKeys "3a"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "W"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "6p"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "p6"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "t"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "p"
WScript.Sleep 300
WshShell.SendKeys "a7"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "W"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "O"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "s6"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "p6"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "t"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "p"
WScript.Sleep 300
WshShell.SendKeys "a7"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "W"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "O"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "p6"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "f7"
WScript.Sleep 300
WshShell.SendKeys "w"
WScript.Sleep 300
WshShell.SendKeys "t"
WScript.Sleep 300
WshShell.SendKeys "o"
WScript.Sleep 300
WshShell.SendKeys "g"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "d6"
WScript.Sleep 300
WshShell.SendKeys "w"
WScript.Sleep 300
WshShell.SendKeys "r"
WScript.Sleep 300
WshShell.SendKeys "i"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "s5"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "a3"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "x"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "p6"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "t"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "p"
WScript.Sleep 300
WshShell.SendKeys "a7"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "W"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "O"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "s6"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "D"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "d"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "p6"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "e"
WScript.Sleep 300
WshShell.SendKeys "t"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "p"
WScript.Sleep 300
WshShell.SendKeys "a7"
WScript.Sleep 300
WshShell.SendKeys "0"
WScript.Sleep 300
WshShell.SendKeys "W"
WScript.Sleep 300
WshShell.SendKeys "u"
WScript.Sleep 300
WshShell.SendKeys "O"
WScript.Sleep 300
WshShell.SendKeys "s"
WScript.Sleep 300
WshShell.SendKeys "a"
WScript.Sleep 300
WshShell.SendKeys "p6"