set wshshell = wscript.CreateObject("wscript.shell")

set computerVoice  = CreateObject("SAPI.spvoice")

set computerVoice.voice = computerVoice.GetVoices.Item(0)

computerVoice.speak "The Für Elise is about to start"
wscript.sleep 500

computerVoice.speak "The Code was made by TheDiamondOG Für Elise is made by Beethoven And all of the code is on github link will show after the song is over."
wscript.sleep 500

computerVoice.speak "Enjoy the song and make shore piano is ready"
wscript.sleep 1000

computerVoice.speak "3"
wscript.sleep 500

computerVoice.speak "2"
wscript.sleep 500

computerVoice.speak "1"
wscript.sleep 500

computerVoice.speak "Starting"
wscript.sleep 500

wscript.sleep 3000
WshShell.SendKeys "f"
WScript.Sleep 220
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "p6"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "t"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "p"
WScript.Sleep 200
WshShell.SendKeys "3a"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "O"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "6s"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "p6"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "t"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "p"
WScript.Sleep 200
WshShell.SendKeys "3a"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "W"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "6p"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "p6"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "t"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "p"
WScript.Sleep 200
WshShell.SendKeys "3a"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "O"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "6s"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "p6"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "t"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "p"
WScript.Sleep 200
WshShell.SendKeys "3a"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "W"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "6p"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "t"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "p"
WScript.Sleep 200
WshShell.SendKeys "3a"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "W"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "6p"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "8f"
WScript.Sleep 200
WshShell.SendKeys "w"
WScript.Sleep 200
WshShell.SendKeys "t"
WScript.Sleep 200
WshShell.SendKeys "o"
WScript.Sleep 200
WshShell.SendKeys "g"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "5d"
WScript.Sleep 200
WshShell.SendKeys "w"
WScript.Sleep 200
WshShell.SendKeys "r"
WScript.Sleep 200
WshShell.SendKeys "i"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "6s"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "3a"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "x"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "p6"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "t"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "p"
WScript.Sleep 200
WshShell.SendKeys "3a"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "W"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "6p"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "p6"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "t"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "p"
WScript.Sleep 200
WshShell.SendKeys "a7"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "W"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "O"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "s6"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "p6"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "t"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "p"
WScript.Sleep 200
WshShell.SendKeys "a7"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "W"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "O"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "p6"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "f7"
WScript.Sleep 200
WshShell.SendKeys "w"
WScript.Sleep 200
WshShell.SendKeys "t"
WScript.Sleep 200
WshShell.SendKeys "o"
WScript.Sleep 200
WshShell.SendKeys "g"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "d6"
WScript.Sleep 200
WshShell.SendKeys "w"
WScript.Sleep 200
WshShell.SendKeys "r"
WScript.Sleep 200
WshShell.SendKeys "i"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "s5"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "a3"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "x"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "p6"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "t"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "p"
WScript.Sleep 200
WshShell.SendKeys "a7"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "W"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "O"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "s6"
WScript.Sleep 300
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "D"
WScript.Sleep 200
WshShell.SendKeys "f"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "d"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "p6"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "e"
WScript.Sleep 200
WshShell.SendKeys "t"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "p"
WScript.Sleep 200
WshShell.SendKeys "a7"
WScript.Sleep 200
WshShell.SendKeys "0"
WScript.Sleep 200
WshShell.SendKeys "W"
WScript.Sleep 200
WshShell.SendKeys "u"
WScript.Sleep 200
WshShell.SendKeys "O"
WScript.Sleep 200
WshShell.SendKeys "s"
WScript.Sleep 200
WshShell.SendKeys "a"
WScript.Sleep 200
WshShell.SendKeys "p6"

computerVoice.speak "Song is finished hoped you enjoyed it."
wscript.sleep 500

computerVoice.speak "Now showing links please don't click off before it's finished"
wscript.sleep 100

wshshell.run "Notepad"
wscript.sleep 2000
wshshell.AppActivate "Notepad"
WScript.Sleep 500

WshShell.SendKeys "https://github.com/TheDiamondOG/The-Fur-Elise-vbs-Vurchidal-Piano-Play"
WScript.Sleep 200

WshShell.SendKeys " "
WScript.Sleep 200

WshShell.SendKeys "https://www.youtube.com/channel/UCokoGiJffjGyo1XCxM1DCxg"
WScript.Sleep 200

WshShell.SendKeys " "
WScript.Sleep 200

WshShell.SendKeys "https://twitch.tv/thediamondog_yt"
WScript.Sleep 200

WshShell.SendKeys " "
WScript.Sleep 200

WshShell.SendKeys "https://github.com/TheDiamondOG"
WScript.Sleep 200